/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptRouteComponentRouteImport } from './routes/receipt/RouteComponent'
import { Route as ParceNotFoundRouteImport } from './routes/parce/not-found'
import { Route as ParceRoomIdRouteImport } from './routes/parce/$roomId'
import { Route as ReceiptReviewNotFoundRouteImport } from './routes/receipt/review.not-found'
import { Route as ReceiptReviewReceiptIdRouteImport } from './routes/receipt/review.$receiptId'
import { Route as ReceiptRouteComponent1RouteImport } from './routes/receipt/RouteComponent.1'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptRouteComponentRoute = ReceiptRouteComponentRouteImport.update({
  id: '/receipt/RouteComponent',
  path: '/receipt/RouteComponent',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceNotFoundRoute = ParceNotFoundRouteImport.update({
  id: '/parce/not-found',
  path: '/parce/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceRoomIdRoute = ParceRoomIdRouteImport.update({
  id: '/parce/$roomId',
  path: '/parce/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptReviewNotFoundRoute = ReceiptReviewNotFoundRouteImport.update({
  id: '/receipt/review/not-found',
  path: '/receipt/review/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptReviewReceiptIdRoute = ReceiptReviewReceiptIdRouteImport.update({
  id: '/receipt/review/$receiptId',
  path: '/receipt/review/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptRouteComponent1Route = ReceiptRouteComponent1RouteImport.update({
  id: '/1',
  path: '/1',
  getParentRoute: () => ReceiptRouteComponentRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/upload': typeof UploadRoute
  '/parce/$roomId': typeof ParceRoomIdRoute
  '/parce/not-found': typeof ParceNotFoundRoute
  '/receipt/RouteComponent': typeof ReceiptRouteComponentRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/receipt/RouteComponent/1': typeof ReceiptRouteComponent1Route
  '/receipt/review/$receiptId': typeof ReceiptReviewReceiptIdRoute
  '/receipt/review/not-found': typeof ReceiptReviewNotFoundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/upload': typeof UploadRoute
  '/parce/$roomId': typeof ParceRoomIdRoute
  '/parce/not-found': typeof ParceNotFoundRoute
  '/receipt/RouteComponent': typeof ReceiptRouteComponentRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/receipt/RouteComponent/1': typeof ReceiptRouteComponent1Route
  '/receipt/review/$receiptId': typeof ReceiptReviewReceiptIdRoute
  '/receipt/review/not-found': typeof ReceiptReviewNotFoundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/upload': typeof UploadRoute
  '/parce/$roomId': typeof ParceRoomIdRoute
  '/parce/not-found': typeof ParceNotFoundRoute
  '/receipt/RouteComponent': typeof ReceiptRouteComponentRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/receipt/RouteComponent/1': typeof ReceiptRouteComponent1Route
  '/receipt/review/$receiptId': typeof ReceiptReviewReceiptIdRoute
  '/receipt/review/not-found': typeof ReceiptReviewNotFoundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/upload'
    | '/parce/$roomId'
    | '/parce/not-found'
    | '/receipt/RouteComponent'
    | '/api/auth/$'
    | '/receipt/RouteComponent/1'
    | '/receipt/review/$receiptId'
    | '/receipt/review/not-found'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/upload'
    | '/parce/$roomId'
    | '/parce/not-found'
    | '/receipt/RouteComponent'
    | '/api/auth/$'
    | '/receipt/RouteComponent/1'
    | '/receipt/review/$receiptId'
    | '/receipt/review/not-found'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/upload'
    | '/parce/$roomId'
    | '/parce/not-found'
    | '/receipt/RouteComponent'
    | '/api/auth/$'
    | '/receipt/RouteComponent/1'
    | '/receipt/review/$receiptId'
    | '/receipt/review/not-found'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  UploadRoute: typeof UploadRoute
  ParceRoomIdRoute: typeof ParceRoomIdRoute
  ParceNotFoundRoute: typeof ParceNotFoundRoute
  ReceiptRouteComponentRoute: typeof ReceiptRouteComponentRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ReceiptReviewReceiptIdRoute: typeof ReceiptReviewReceiptIdRoute
  ReceiptReviewNotFoundRoute: typeof ReceiptReviewNotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/RouteComponent': {
      id: '/receipt/RouteComponent'
      path: '/receipt/RouteComponent'
      fullPath: '/receipt/RouteComponent'
      preLoaderRoute: typeof ReceiptRouteComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parce/not-found': {
      id: '/parce/not-found'
      path: '/parce/not-found'
      fullPath: '/parce/not-found'
      preLoaderRoute: typeof ParceNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parce/$roomId': {
      id: '/parce/$roomId'
      path: '/parce/$roomId'
      fullPath: '/parce/$roomId'
      preLoaderRoute: typeof ParceRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/review/not-found': {
      id: '/receipt/review/not-found'
      path: '/receipt/review/not-found'
      fullPath: '/receipt/review/not-found'
      preLoaderRoute: typeof ReceiptReviewNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/review/$receiptId': {
      id: '/receipt/review/$receiptId'
      path: '/receipt/review/$receiptId'
      fullPath: '/receipt/review/$receiptId'
      preLoaderRoute: typeof ReceiptReviewReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/RouteComponent/1': {
      id: '/receipt/RouteComponent/1'
      path: '/1'
      fullPath: '/receipt/RouteComponent/1'
      preLoaderRoute: typeof ReceiptRouteComponent1RouteImport
      parentRoute: typeof ReceiptRouteComponentRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReceiptRouteComponentRouteChildren {
  ReceiptRouteComponent1Route: typeof ReceiptRouteComponent1Route
}

const ReceiptRouteComponentRouteChildren: ReceiptRouteComponentRouteChildren = {
  ReceiptRouteComponent1Route: ReceiptRouteComponent1Route,
}

const ReceiptRouteComponentRouteWithChildren =
  ReceiptRouteComponentRoute._addFileChildren(
    ReceiptRouteComponentRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  UploadRoute: UploadRoute,
  ParceRoomIdRoute: ParceRoomIdRoute,
  ParceNotFoundRoute: ParceNotFoundRoute,
  ReceiptRouteComponentRoute: ReceiptRouteComponentRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ReceiptReviewReceiptIdRoute: ReceiptReviewReceiptIdRoute,
  ReceiptReviewNotFoundRoute: ReceiptReviewNotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
