/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UploadRouteRouteImport } from './routes/upload/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptReviewRouteRouteImport } from './routes/receipt/review/route'
import { Route as ReceiptParceRouteRouteImport } from './routes/receipt/parce/route'
import { Route as ReceiptReviewReceiptIdRouteImport } from './routes/receipt/review/$receiptId'
import { Route as ReceiptParceRoomIdRouteImport } from './routes/receipt/parce/$roomId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRouteRoute = UploadRouteRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptReviewRouteRoute = ReceiptReviewRouteRouteImport.update({
  id: '/receipt/review',
  path: '/receipt/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptParceRouteRoute = ReceiptParceRouteRouteImport.update({
  id: '/receipt/parce',
  path: '/receipt/parce',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptReviewReceiptIdRoute = ReceiptReviewReceiptIdRouteImport.update({
  id: '/$receiptId',
  path: '/$receiptId',
  getParentRoute: () => ReceiptReviewRouteRoute,
} as any)
const ReceiptParceRoomIdRoute = ReceiptParceRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => ReceiptParceRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRoute
  '/upload': typeof UploadRouteRoute
  '/login': typeof LoginRoute
  '/receipt/parce': typeof ReceiptParceRouteRouteWithChildren
  '/receipt/review': typeof ReceiptReviewRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/receipt/parce/$roomId': typeof ReceiptParceRoomIdRoute
  '/receipt/review/$receiptId': typeof ReceiptReviewReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRoute
  '/upload': typeof UploadRouteRoute
  '/login': typeof LoginRoute
  '/receipt/parce': typeof ReceiptParceRouteRouteWithChildren
  '/receipt/review': typeof ReceiptReviewRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/receipt/parce/$roomId': typeof ReceiptParceRoomIdRoute
  '/receipt/review/$receiptId': typeof ReceiptReviewReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRoute
  '/upload': typeof UploadRouteRoute
  '/login': typeof LoginRoute
  '/receipt/parce': typeof ReceiptParceRouteRouteWithChildren
  '/receipt/review': typeof ReceiptReviewRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/receipt/parce/$roomId': typeof ReceiptParceRoomIdRoute
  '/receipt/review/$receiptId': typeof ReceiptReviewReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/upload'
    | '/login'
    | '/receipt/parce'
    | '/receipt/review'
    | '/api/auth/$'
    | '/receipt/parce/$roomId'
    | '/receipt/review/$receiptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/upload'
    | '/login'
    | '/receipt/parce'
    | '/receipt/review'
    | '/api/auth/$'
    | '/receipt/parce/$roomId'
    | '/receipt/review/$receiptId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/upload'
    | '/login'
    | '/receipt/parce'
    | '/receipt/review'
    | '/api/auth/$'
    | '/receipt/parce/$roomId'
    | '/receipt/review/$receiptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRoute
  UploadRouteRoute: typeof UploadRouteRoute
  LoginRoute: typeof LoginRoute
  ReceiptParceRouteRoute: typeof ReceiptParceRouteRouteWithChildren
  ReceiptReviewRouteRoute: typeof ReceiptReviewRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/review': {
      id: '/receipt/review'
      path: '/receipt/review'
      fullPath: '/receipt/review'
      preLoaderRoute: typeof ReceiptReviewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/parce': {
      id: '/receipt/parce'
      path: '/receipt/parce'
      fullPath: '/receipt/parce'
      preLoaderRoute: typeof ReceiptParceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/review/$receiptId': {
      id: '/receipt/review/$receiptId'
      path: '/$receiptId'
      fullPath: '/receipt/review/$receiptId'
      preLoaderRoute: typeof ReceiptReviewReceiptIdRouteImport
      parentRoute: typeof ReceiptReviewRouteRoute
    }
    '/receipt/parce/$roomId': {
      id: '/receipt/parce/$roomId'
      path: '/$roomId'
      fullPath: '/receipt/parce/$roomId'
      preLoaderRoute: typeof ReceiptParceRoomIdRouteImport
      parentRoute: typeof ReceiptParceRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReceiptParceRouteRouteChildren {
  ReceiptParceRoomIdRoute: typeof ReceiptParceRoomIdRoute
}

const ReceiptParceRouteRouteChildren: ReceiptParceRouteRouteChildren = {
  ReceiptParceRoomIdRoute: ReceiptParceRoomIdRoute,
}

const ReceiptParceRouteRouteWithChildren =
  ReceiptParceRouteRoute._addFileChildren(ReceiptParceRouteRouteChildren)

interface ReceiptReviewRouteRouteChildren {
  ReceiptReviewReceiptIdRoute: typeof ReceiptReviewReceiptIdRoute
}

const ReceiptReviewRouteRouteChildren: ReceiptReviewRouteRouteChildren = {
  ReceiptReviewReceiptIdRoute: ReceiptReviewReceiptIdRoute,
}

const ReceiptReviewRouteRouteWithChildren =
  ReceiptReviewRouteRoute._addFileChildren(ReceiptReviewRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRoute,
  UploadRouteRoute: UploadRouteRoute,
  LoginRoute: LoginRoute,
  ReceiptParceRouteRoute: ReceiptParceRouteRouteWithChildren,
  ReceiptReviewRouteRoute: ReceiptReviewRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
