/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedUploadRouteImport } from './routes/_authed/upload'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthedAcceptInviteRouteImport } from './routes/_authed/acceptInvite'
import { Route as ReceiptParceRouteRouteImport } from './routes/receipt/parce/route'
import { Route as ReceiptParceRoomIdRouteImport } from './routes/receipt/parce/$roomId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiReceiptImageRoomRoomIdRouteImport } from './routes/api/receipt-image/room/$roomId'
import { Route as ApiReceiptImageReceiptReceiptIdRouteImport } from './routes/api/receipt-image/receipt/$receiptId'
import { Route as AuthedReceiptReviewReceiptIdRouteImport } from './routes/_authed/receipt.review.$receiptId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/terms.lazy').then((d) => d.Route))
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/privacy.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUploadRoute = AuthedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAcceptInviteRoute = AuthedAcceptInviteRouteImport.update({
  id: '/acceptInvite',
  path: '/acceptInvite',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ReceiptParceRouteRoute = ReceiptParceRouteRouteImport.update({
  id: '/receipt/parce',
  path: '/receipt/parce',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptParceRoomIdRoute = ReceiptParceRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => ReceiptParceRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceiptImageRoomRoomIdRoute =
  ApiReceiptImageRoomRoomIdRouteImport.update({
    id: '/api/receipt-image/room/$roomId',
    path: '/api/receipt-image/room/$roomId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReceiptImageReceiptReceiptIdRoute =
  ApiReceiptImageReceiptReceiptIdRouteImport.update({
    id: '/api/receipt-image/receipt/$receiptId',
    path: '/api/receipt-image/receipt/$receiptId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedReceiptReviewReceiptIdRoute =
  AuthedReceiptReviewReceiptIdRouteImport.update({
    id: '/receipt/review/$receiptId',
    path: '/receipt/review/$receiptId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/receipt/parce': typeof ReceiptParceRouteRouteWithChildren
  '/acceptInvite': typeof AuthedAcceptInviteRoute
  '/account': typeof AuthedAccountRoute
  '/upload': typeof AuthedUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/receipt/parce/$roomId': typeof ReceiptParceRoomIdRoute
  '/receipt/review/$receiptId': typeof AuthedReceiptReviewReceiptIdRoute
  '/api/receipt-image/receipt/$receiptId': typeof ApiReceiptImageReceiptReceiptIdRoute
  '/api/receipt-image/room/$roomId': typeof ApiReceiptImageRoomRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/receipt/parce': typeof ReceiptParceRouteRouteWithChildren
  '/acceptInvite': typeof AuthedAcceptInviteRoute
  '/account': typeof AuthedAccountRoute
  '/upload': typeof AuthedUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/receipt/parce/$roomId': typeof ReceiptParceRoomIdRoute
  '/receipt/review/$receiptId': typeof AuthedReceiptReviewReceiptIdRoute
  '/api/receipt-image/receipt/$receiptId': typeof ApiReceiptImageReceiptReceiptIdRoute
  '/api/receipt-image/room/$roomId': typeof ApiReceiptImageRoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/receipt/parce': typeof ReceiptParceRouteRouteWithChildren
  '/_authed/acceptInvite': typeof AuthedAcceptInviteRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/upload': typeof AuthedUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/receipt/parce/$roomId': typeof ReceiptParceRoomIdRoute
  '/_authed/receipt/review/$receiptId': typeof AuthedReceiptReviewReceiptIdRoute
  '/api/receipt-image/receipt/$receiptId': typeof ApiReceiptImageReceiptReceiptIdRoute
  '/api/receipt-image/room/$roomId': typeof ApiReceiptImageRoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/receipt/parce'
    | '/acceptInvite'
    | '/account'
    | '/upload'
    | '/api/auth/$'
    | '/receipt/parce/$roomId'
    | '/receipt/review/$receiptId'
    | '/api/receipt-image/receipt/$receiptId'
    | '/api/receipt-image/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/receipt/parce'
    | '/acceptInvite'
    | '/account'
    | '/upload'
    | '/api/auth/$'
    | '/receipt/parce/$roomId'
    | '/receipt/review/$receiptId'
    | '/api/receipt-image/receipt/$receiptId'
    | '/api/receipt-image/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/receipt/parce'
    | '/_authed/acceptInvite'
    | '/_authed/account'
    | '/_authed/upload'
    | '/api/auth/$'
    | '/receipt/parce/$roomId'
    | '/_authed/receipt/review/$receiptId'
    | '/api/receipt-image/receipt/$receiptId'
    | '/api/receipt-image/room/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ReceiptParceRouteRoute: typeof ReceiptParceRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiReceiptImageReceiptReceiptIdRoute: typeof ApiReceiptImageReceiptReceiptIdRoute
  ApiReceiptImageRoomRoomIdRoute: typeof ApiReceiptImageRoomRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/upload': {
      id: '/_authed/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthedUploadRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/acceptInvite': {
      id: '/_authed/acceptInvite'
      path: '/acceptInvite'
      fullPath: '/acceptInvite'
      preLoaderRoute: typeof AuthedAcceptInviteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/receipt/parce': {
      id: '/receipt/parce'
      path: '/receipt/parce'
      fullPath: '/receipt/parce'
      preLoaderRoute: typeof ReceiptParceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/parce/$roomId': {
      id: '/receipt/parce/$roomId'
      path: '/$roomId'
      fullPath: '/receipt/parce/$roomId'
      preLoaderRoute: typeof ReceiptParceRoomIdRouteImport
      parentRoute: typeof ReceiptParceRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipt-image/room/$roomId': {
      id: '/api/receipt-image/room/$roomId'
      path: '/api/receipt-image/room/$roomId'
      fullPath: '/api/receipt-image/room/$roomId'
      preLoaderRoute: typeof ApiReceiptImageRoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipt-image/receipt/$receiptId': {
      id: '/api/receipt-image/receipt/$receiptId'
      path: '/api/receipt-image/receipt/$receiptId'
      fullPath: '/api/receipt-image/receipt/$receiptId'
      preLoaderRoute: typeof ApiReceiptImageReceiptReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/receipt/review/$receiptId': {
      id: '/_authed/receipt/review/$receiptId'
      path: '/receipt/review/$receiptId'
      fullPath: '/receipt/review/$receiptId'
      preLoaderRoute: typeof AuthedReceiptReviewReceiptIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedAcceptInviteRoute: typeof AuthedAcceptInviteRoute
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedUploadRoute: typeof AuthedUploadRoute
  AuthedReceiptReviewReceiptIdRoute: typeof AuthedReceiptReviewReceiptIdRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAcceptInviteRoute: AuthedAcceptInviteRoute,
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedUploadRoute: AuthedUploadRoute,
  AuthedReceiptReviewReceiptIdRoute: AuthedReceiptReviewReceiptIdRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface ReceiptParceRouteRouteChildren {
  ReceiptParceRoomIdRoute: typeof ReceiptParceRoomIdRoute
}

const ReceiptParceRouteRouteChildren: ReceiptParceRouteRouteChildren = {
  ReceiptParceRoomIdRoute: ReceiptParceRoomIdRoute,
}

const ReceiptParceRouteRouteWithChildren =
  ReceiptParceRouteRoute._addFileChildren(ReceiptParceRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ReceiptParceRouteRoute: ReceiptParceRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiReceiptImageReceiptReceiptIdRoute: ApiReceiptImageReceiptReceiptIdRoute,
  ApiReceiptImageRoomRoomIdRoute: ApiReceiptImageRoomRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
